# Generated by Django 6.0 on 2026-04-27 00:00

import uuid

import api.utils
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name = "AuthenticationToken",
            fields = [
                (
                    "id",
                    models.UUIDField(
                        default = uuid.uuid4,
                        editable = False,
                        primary_key = True,
                        serialize = False,
                        unique = True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name = "Product",
            fields = [
                (
                    "id",
                    models.UUIDField(
                        default = uuid.uuid4,
                        editable = False,
                        primary_key = True,
                        serialize = False,
                        unique = True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices = [
                            ("suit", "\u041a\u043e\u0441\u0442\u044e\u043c"),
                            ("shape", "\u0424\u0438\u0433\u0443\u0440\u043a\u0430"),
                            ("comics", "\u041a\u043e\u043c\u0438\u043a\u0441\u044b"),
                        ],
                        max_length = 20,
                        verbose_name = "\u041a\u0430\u0442\u0435\u0433\u043e\u0440\u0438\u044f",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length = 50,
                        verbose_name = "\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435",
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        validators = [
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name = "\u0426\u0435\u043d\u0430",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        max_length = 1000,
                        verbose_name = "\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default = django.utils.timezone.now,
                        verbose_name = "\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f",
                    ),
                ),
            ],
            options = {
                "verbose_name": "\u0422\u043e\u0432\u0430\u0440",
                "verbose_name_plural": "\u0422\u043e\u0432\u0430\u0440\u044b",
                "ordering": ["name", "creation_date"],
            },
        ),
        migrations.CreateModel(
            name = "UserImage",
            fields = [
                (
                    "user",
                    models.OneToOneField(
                        on_delete = django.db.models.deletion.CASCADE,
                        primary_key = True,
                        related_name = "image",
                        serialize = False,
                        to = settings.AUTH_USER_MODEL,
                        verbose_name = "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default = None,
                        null = True,
                        upload_to = api.utils.get_user_image_path,
                        verbose_name = "\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name = "AuthenticationRequest",
            fields = [
                (
                    "token",
                    models.OneToOneField(
                        on_delete = django.db.models.deletion.CASCADE,
                        primary_key = True,
                        serialize = False,
                        to = "api.authenticationtoken",
                    ),
                ),
                ("telegram_id", models.BigIntegerField()),
                ("telegram_username", models.CharField(max_length = 32, null = True)),
                ("telegram_name", models.CharField(max_length = 128, null = True)),
                ("telegram_image", models.BinaryField(editable = True, null = True)),
            ],
        ),
        migrations.CreateModel(
            name = "Order",
            fields = [
                (
                    "id",
                    models.UUIDField(
                        default = uuid.uuid4,
                        editable = False,
                        primary_key = True,
                        serialize = False,
                        unique = True,
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        default = 0,
                        validators = [django.core.validators.MinValueValidator(0)],
                        verbose_name = "\u0426\u0435\u043d\u0430",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices = [
                            (
                                "pending_payment",
                                "\u041e\u0436\u0438\u0434\u0430\u0435\u0442 \u043e\u043f\u043b\u0430\u0442\u044b",
                            ),
                            (
                                "pending_assembly",
                                "\u0421\u043e\u0431\u0438\u0440\u0430\u0435\u0442\u0441\u044f",
                            ),
                            (
                                "pending_pickup",
                                "\u041c\u043e\u0436\u043d\u043e \u0437\u0430\u0431\u0438\u0440\u0430\u0442\u044c",
                            ),
                            ("finished", "\u0417\u0430\u0432\u0435\u0440\u0448\u0435\u043d"),
                            ("cancelled", "\u041e\u0442\u043c\u0435\u043d\u0435\u043d"),
                        ],
                        default = "pending_payment",
                        max_length = 20,
                        verbose_name = "\u0421\u0442\u0430\u0442\u0443\u0441",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        default = django.utils.timezone.now,
                        verbose_name = "\u0414\u0430\u0442\u0430",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.PROTECT,
                        related_name = "orders",
                        to = settings.AUTH_USER_MODEL,
                        verbose_name = "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c",
                    ),
                ),
            ],
            options = {
                "verbose_name": "\u0417\u0430\u043a\u0430\u0437",
                "verbose_name_plural": "\u0417\u0430\u043a\u0430\u0437\u044b",
                "ordering": ["-datetime"],
            },
        ),
        migrations.CreateModel(
            name = "OrderProduct",
            fields = [
                (
                    "id",
                    models.UUIDField(
                        default = uuid.uuid4,
                        editable = False,
                        primary_key = True,
                        serialize = False,
                        unique = True,
                    ),
                ),
                (
                    "price",
                    models.IntegerField(
                        default = 0,
                        validators = [
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100000),
                        ],
                        verbose_name = "\u0426\u0435\u043d\u0430",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        validators = [
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.CASCADE,
                        related_name = "products",
                        to = "api.order",
                        verbose_name = "\u0417\u0430\u043a\u0430\u0437",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.PROTECT,
                        to = "api.product",
                        verbose_name = "\u0422\u043e\u0432\u0430\u0440",
                    ),
                ),
            ],
            options = {
                "verbose_name": "\u0422\u043e\u0432\u0430\u0440 \u0437\u0430\u043a\u0430\u0437\u0430",
                "verbose_name_plural": "\u0422\u043e\u0432\u0430\u0440\u044b \u0437\u0430\u043a\u0430\u0437\u043e\u0432",
            },
        ),
        migrations.CreateModel(
            name = "ProductImage",
            fields = [
                (
                    "id",
                    models.UUIDField(
                        default = uuid.uuid4,
                        editable = False,
                        primary_key = True,
                        serialize = False,
                        unique = True,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        default = None,
                        null = True,
                        upload_to = api.utils.get_product_image_path,
                        verbose_name = "\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.CASCADE,
                        related_name = "images",
                        to = "api.product",
                        verbose_name = "\u0422\u043e\u0432\u0430\u0440",
                    ),
                ),
            ],
            options = {
                "verbose_name": "\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u0435 \u0442\u043e\u0432\u0430\u0440\u0430",
                "verbose_name_plural": "\u0418\u0437\u043e\u0431\u0440\u0430\u0436\u0435\u043d\u0438\u044f \u0442\u043e\u0432\u0430\u0440\u043e\u0432",
            },
        ),
        migrations.CreateModel(
            name = "Cart",
            fields = [
                (
                    "id",
                    models.UUIDField(
                        default = uuid.uuid4,
                        editable = False,
                        primary_key = True,
                        serialize = False,
                        unique = True,
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        default = 1,
                        verbose_name = "\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e",
                    ),
                ),
                (
                    "creation_date",
                    models.DateTimeField(
                        default = django.utils.timezone.now,
                        verbose_name = "\u0414\u0430\u0442\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d\u0438\u044f",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.PROTECT,
                        to = "api.product",
                        verbose_name = "\u0422\u043e\u0432\u0430\u0440",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete = django.db.models.deletion.PROTECT,
                        related_name = "cart",
                        to = settings.AUTH_USER_MODEL,
                        verbose_name = "\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c",
                    ),
                ),
            ],
            options = {
                "verbose_name": "\u0422\u043e\u0432\u0430\u0440\u044b \u0432 \u043a\u043e\u0440\u0437\u0438\u043d\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439",
                "verbose_name_plural": "\u0422\u043e\u0432\u0430\u0440\u044b \u0432 \u043a\u043e\u0440\u0437\u0438\u043d\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439",
                "ordering": ["user__username", "product__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields = ("user", "product"),
                        name = "unique_user_product",
                    ),
                ],
            },
        ),
    ]
