# Generated by Django 6.0 on 2026-03-04 17:46
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        TrigramExtension()
    ]
