# Generated by Django 6.0 on 2026-03-04 17:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_enable_pg_trgm'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='name_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
