# Generated by Django 6.0 on 2026-03-06 17:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product_name_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('pending_assembly', 'Pending Assembly'), ('pending_pickup', 'Pending Pickup'), ('finished', 'Finished'), ('cancelled', 'Cancelled')], default='pending_payment', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('suit', 'Suit'), ('shape', 'Shape'), ('comics', 'Comics')], max_length=20),
        )
    ]
