# Generated by Django 6.0 on 2026-03-06 17:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0004_order_datetime_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'order',
            name = 'datetime',
            field = models.DateTimeField(default = django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name = 'orderproduct',
            name = 'order',
            field = models.ForeignKey(on_delete = django.db.models.deletion.PROTECT, related_name = 'products',
                                      to = 'api.order'),
        )
    ]
