# Generated by Django 6.0 on 2026-04-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
    ]
