# Generated by Django 6.0 on 2026-04-23 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_product_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='creation_date',
        ),
    ]
