# Generated by Django 6.0 on 2026-04-23 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_product_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['creation_date', 'name'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
