# Generated by Django 6.0 on 2026-04-24 13:55

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['user__username', 'product__name'], 'verbose_name': 'Товары в корзине пользователей', 'verbose_name_plural': 'Товары в корзине пользователей'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-datetime'], 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'creation_date'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='cart',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Ожидает оплаты'), ('pending_assembly', 'Собирается'), ('pending_pickup', 'Можно забирать'), ('finished', 'Завершен'), ('cancelled', 'Отменен')], default='pending_payment', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='amount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Количество'),
        ),
    ]
