# Generated by Django 6.0.3 on 2026-04-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_tag_producttag_product_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name = 'product',
            name = 'source_url',
            field = models.URLField(blank = True, null = True, verbose_name = 'Ссылка на источник'),
        ),
    ]
