# Generated by Django 6.0.3 on 2026-05-11 12:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_productreport_id_alter_producttag_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='remaining',
            field=models.IntegerField(default=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
